name: Secure Docker CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t secure-pipeline-demo:${{ github.sha }} .

    - name: Scan with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'secure-pipeline-demo:${{ github.sha }}'
        severity: 'CRITICAL,HIGH'
        exit-code: '1'
        format: 'table'
        ignore-unfixed: true

    - name: Scan with Grype
      uses: anchore/scan-action@v3
      with:
        image: 'secure-pipeline-demo:${{ github.sha }}'
        fail-build: true
        severity-cutoff: high
